
name: "Build ALL"
on: [push]
jobs:
  gradle:
    strategy:
      matrix:
        #TODO -remove comment before ver2 tag
        #os: [ubuntu-latest, macos-latest, windows-latest]
        #version : [11, 17, 18]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 17
          cache: gradle
      - name: "Build the configured project"
        uses: gradle/gradle-build-action@v2
        with:
          arguments: buildAllTasks --scan -x test

      - name: Archive test report
        uses: actions/upload-artifact@v2
        with:
          name: Test report
          path: build/reports/tests/test
