name: "DB - PostgreSQL"
on:
  workflow_run:
    workflows: ["Build ALL"]
    types:
      - completed
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
  release:
    types: [ published ]

jobs:
  push_db_image :
    name: Push Docker image to Docker Hub DB
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: deploy-container-to-registry
        uses: slabstech/action-deploy-container-to-registry@v0.0.1
        with:
            docker-username: ${{ secrets.DOCKER_USERNAME }}
            docker-password: ${{ secrets.DOCKER_PASSWORD }}
            github-actor: ${{ github.actor }}
            github-token: ${{ secrets.GITHUB_TOKEN }}
            github-repository: ${{ github.repository }}
            project-name: shop
            service-name: db-postgresql
            dockerfile-path: ./docker/db/postgresql/Dockerfile