name: "Server SpringBoot"
on:
  workflow_run:
    workflows: ["Build ALL"]
    types:
      - completed
  push:
    branches:
      - deploy_server_container_to_registry
      - main
    tags:
      - 'v*'
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
  release:
    types: [ published ]

jobs:
  push_server_image :
    name : Push Docker image to Docker Hub - server
    runs-on : ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Push to container
        uses: ./.github/actions/deploy-container-to-registry
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          github-actor: ${{ github.actor }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-repository: ${{ github.repository }}
          project-name: revive
          service-type: server
          tech-name: spring-boot
          dockerfile-path: ./docker/server/spring_boot/Dockerfile

